name: FTP Test root upload
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          echo APP_DEBUG=false >> .env
          echo DB_USERNAME=test_username >> .env
          echo DB_PASSWORD=some_password >> .env
          echo "!.env" > .git-ftp-include # Add git untracked file
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
